//
// Created by Vincent Bode on 23/06/2020.
//

#ifndef ASSIGNMENTS_STRINGSEARCH_H
#define ASSIGNMENTS_STRINGSEARCH_H

#define FILE_NAME "britannica.txt"
#define DOCUMENT_SIZE 10093056

#define NUM_QUERIES 24
#define MAX_QUERY_LENGTH ((NUM_QUERIES / 4) + 5)

#endif //ASSIGNMENTS_STRINGSEARCH_H
